### ISSUE TITLE
HTTPConnectionManager.UseRemoteAddress is *types.BoolValue not bool

### ISSUE THREAD

**Issue by davecheney** [envoyproxy/go-control-plane#182]
Hello,

Some properties of `HTTPConnectionManager` are booleans, `Http1ProtocolOptions.AcceptHttp_10` for example, however others like `UseRemoteAddress` and `NormalizePath` are the less convenient `*types.BoolValue`.

Is it possible to convert the latter to be more like the former?

**Comment by kyessenov** [comment]
This is controlled through gogoproto annotations. In general, this cannot be automated, since the reason for using wrapper types in envoy xDS is because of the inconsistent defaulting logic. E.g. if a boolean flag defaults to true in envoy, then we cannot use protobuf bool since it defaults to false.

However, if the defaults do match, then it is reasonable to annotate xDS APIs with the annotations to improve usability.
For example, adding nonnullable annotations would get rid of the pointer to `types.BoolValue`, which is a little bit better. See https://github.com/envoyproxy/data-plane-api/blob/cb050ce1e502dd7b75b10bf09c1ec81406db71e8/envoy/api/v2/core/address.proto#L87, for an example.

**Comment by davecheney** [comment]
Thank you for the information. I’ll see what I can cook up.

**Comment by kyessenov** [comment]
This is now frozen to follow the standard golang/protobuf generation for golang. It is always a message for optional primitives.
