### ISSUE TITLE
PLEASE CHECK

### ISSUE THREAD

**Issue by bcba25** [envoyproxy/go-control-plane#268]
This issue is addressed to the core developers and creators of the envoy proxy. I've been using your software for quite awhile and my honest feedback is very positive, despite the fact that there is LACK of documentation and tutorials related to your products. I've been searching for video courses, articles etc but in fact found only a brief information on how to setup and configure your products. Majority of the information were obtained by looking at the examples at the Github. Not sure whether I'm the only one struggling with your products or not, but my honest wish is that you can somehow improve your documentation section on the main website to include real life examples or maybe you can write some tutorials for envoy proxy and consul since majority of the issues on Github on your repos are open for days and some people even not getting any response at all. 

Sorry for the title of this issue, you can rename it or close, but I would be really thankful if you can reply on this one. Thank you !

**Comment by kyessenov** [comment]
Thanks, we do recognize that the documentation is important but we don't have capacity to do all of it ourselves. Please contribute!

**Comment by bcba25** [comment]
@kyessenov I would definitely contribute and even write the tutorials for somebody but the issue is I can do that because I can't setup it myself )) Hope you guys can setup a basic but detailed guides on that.

**Comment by wicharypawel** [comment]
@bcba25 I have the same feeling. Moreover, I came from .NET world which makes it double hard. People like me have to hoop over language barrier, tooling issues, xDS related knowledge and last but not least figure out how on earth make this work.

Just a brief summary:
- It took me a few hours to setup Istio Pilot (alternative control plane). 
- It took me 2 days to setup java-control-plane (because of insufficient documentation)
- After few hours, I was not successfull with Go-control-plane. It has started and stopped a second after. 

I think Istio is the most capable product with tons of options. However, it is easy to get into it because of well written documentation.

Just a few paragraphs and "paint made" drawing would save the world of many people trying to setup this tool.

**Comment by acnodal-tc** [comment]
aae778bbe0a2c52846d35f2ba0607d0c584d7f3b just landed and you might find it helpful.

**Comment by kyessenov** [comment]
@wicharypawel This repo is not meant to be a product. It's a building block and a space to share common envoy management code between folks who build in-house control planes or some user-facing "mesh" type product. I just want to make expectations clear, since the scope is limited by design.

**Comment by wicharypawel** [comment]
Don't get me wrong, I am not agains anybody. Moreover, it is appreciated that such work is open to public. However, as this is a public repository, hosted under envoy proxy org and people like me will eventually get here. Unless you make it clear in main README that repository is "internal" people will leave feedback.
