### ISSUE TITLE
Setting the snapshot in the cache should hash the node ID

### ISSUE THREAD

**Issue by jpeach** [envoyproxy/go-control-plane#302]
`(*snapshotCache) SetSnapshot()` takes a node ID parameter but doesn't hash it before indexing the snapshots map. This means that if you bring your own NodeHash implementation, the cache won't find entries consistently.

**Comment by jpeach** [comment]
Hmm, this is consistent across `GetStatusInfo` and `GetSnapshot`. Seems inconsistent and surprising that the caller has to pass the hashed node ID into these functions, but the node ID used in `CreateWatch` and `Fetch` is internally hashed.

**Comment by mattklein123** [comment]
cc @jessicayuen @jyotimahapatra can you take a look?

**Comment by jyotimahapatra** [comment]
@jpeach i see your point. Here's few of my observations:
1. The hashing function used in `SnapshotCache.CreateWatch` is provided by the user [here](https://github.com/envoyproxy/go-control-plane/blob/master/pkg/cache/v2/simple.go#L101). 
2. The hashing function is only applicable in `CreateWatch` because the `DiscoveryRequest` is only available in the context of a xDS request. `SetSnapshot` and other functions are not called from the same context, and hence do not have the access to `DiscoveryRequest` and hence unable to use the hashing function. The author of the hashing function is aware of the DiscoveryRequest aggregation patterns and fills up the cache entries individually.

Since the call contexts of the functions are different, the same hashing function cannot be applied. I guess that could be the reason behind putting the responsibility of deciding the hash on the user before calling `SnapshotCache` related functions.

Having said that, we could think about how to make the call pattern more coherent.

**Comment by jpeach** [comment]
@jyotimahapatra This would make the interface unambiguous, though it is not source compatible:

```
diff --git pkg/cache/v2/simple.go pkg/cache/v2/simple.go
index 69cc0c6..9320337 100644
--- pkg/cache/v2/simple.go
+++ pkg/cache/v2/simple.go
@@ -48,13 +48,13 @@ type SnapshotCache interface {
 	SetSnapshot(node string, snapshot Snapshot) error
 
 	// GetSnapshots gets the snapshot for a node.
-	GetSnapshot(node string) (Snapshot, error)
+	GetSnapshot(node NodeID) (Snapshot, error)
 
 	// ClearSnapshot removes all status and snapshot information associated with a node.
-	ClearSnapshot(node string)
+	ClearSnapshot(node NodeID)
 
 	// GetStatusInfo retrieves status information for a node ID.
-	GetStatusInfo(string) StatusInfo
+	GetStatusInfo(node NodeID) StatusInfo
 
 	// GetStatusKeys retrieves node IDs for all statuses.
 	GetStatusKeys() []string
diff --git pkg/cache/v2/status.go pkg/cache/v2/status.go
index c1feca7..c642630 100644
--- pkg/cache/v2/status.go
+++ pkg/cache/v2/status.go
@@ -21,21 +21,23 @@ import (
 	core "github.com/envoyproxy/go-control-plane/envoy/api/v2/core"
 )
 
+type NodeID string
+
 // NodeHash computes string identifiers for Envoy nodes.
 type NodeHash interface {
 	// ID function defines a unique string identifier for the remote Envoy node.
-	ID(node *core.Node) string
+	ID(node *core.Node) NodeID
 }
 
 // IDHash uses ID field as the node hash.
 type IDHash struct{}
 
 // ID uses the node ID field
-func (IDHash) ID(node *core.Node) string {
+func (IDHash) ID(node *core.Node) NodeID {
 	if node == nil {
 		return ""
 	}
-	return node.Id
+	return NodeID(node.Id)
 }
 
 var _ NodeHash = IDHash{}

```
