### ISSUE TITLE
Server is leaking goroutines

### ISSUE THREAD

**Issue by easwars** [envoyproxy/go-control-plane#370]
In gRPC-Go, we are trying to move our tests to use the management server implementation found here instead of using our own fake xDS management server.

Our tests run with a leak checker which waits for ten seconds after test completion to make sure that that there are no leaked goroutines. I see my tests fail every now and then with the following goroutine being leaked:
```
grpctest.go:39: Leaked goroutine: goroutine 758 [chan send]:
  github.com/envoyproxy/go-control-plane/pkg/server/sotw/v3.(*server).StreamHandler.func1(0x27b4118, 0xc00032c3e0, 0xc00043c0e0, 0xc000a9a4e0)
    /Users/easwars/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.7/pkg/server/sotw/v3/server.go:409 +0x45
  created by github.com/envoyproxy/go-control-plane/pkg/server/sotw/v3.(*server).StreamHandler
    /Users/easwars/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.7/pkg/server/sotw/v3/server.go:399 +0x99
grpctest.go:60: Leak check disabled for future tests
```

The goroutine being leaked is the one spawned here:
```golang
// StreamHandler converts a blocking read call to channels and initiates stream processing
func (s *server) StreamHandler(stream Stream, typeURL string) error {
	// a channel for receiving incoming requests
	reqCh := make(chan *discovery.DiscoveryRequest)
	reqStop := int32(0)
	go func() {
		for {
			req, err := stream.Recv()
			if atomic.LoadInt32(&reqStop) != 0 {
				return
			}
			if err != nil {
				close(reqCh)
				return
			}
			reqCh <- req
		}
	}()

	err := s.process(stream, reqCh, typeURL)

	// prevents writing to a closed channel if send failed on blocked recv
	// TODO(kuat) figure out how to unblock recv through gRPC API
	atomic.StoreInt32(&reqStop, 1)

	return err
}
```

I still don't understand the exact sequence of events which lead to the write to `reqCh` getting blocked forever here. But a simple fix to this would be to replace the write to the channel with a select:

```golang
select {
  case reqCh <- req:
  case <-s.ctx.Done():
    return
}
```

Do you think this would be a reasonable fix?

**Comment by kyessenov** [comment]
I think the sequence is:
1. process() completes
2. go-routine blocks on line `reqCh <- req`
3. `reqStop` is updated.
4. Step 2 never unblocks as the receiver is gone.

The context done fix would work, but it only reaps the go-routines at the end I think. Let me think how to make it better.

**Comment by kyessenov** [comment]
I'll follow up with a change to stop collecting zombie go-routines.

**Comment by fxposter** [comment]
@kyessenov what about this?

	reqCh := make(chan *discovery.DiscoveryRequest)
	reqStop := make(chan struct{})
	go func() {
		for {
			req, err := stream.Recv()
			if err != nil {
				close(reqCh)
				return
			}
			select {
			case reqCh <- req:
			case <-reqStop:
				close(reqCh)
				return
			}
		}
	}()

	err := s.process(stream, reqCh, typeURL)

	close(reqStop)

**Comment by kyessenov** [comment]
Do you think it can block forever in `Recv()`? Doesn't closing `reqStop` exits the for loop? It may be buggy, I'm just not seeing it.

**Comment by fxposter** [comment]
Well, it is totally possible in theory, quite unlikely, but possible. Look at `process` method and check when can it finish:

https://github.com/envoyproxy/go-control-plane/blob/e42c3410afe12ff0ab77dbd5954e688a4ca59036/pkg/server/sotw/v2/server.go#L186

https://github.com/envoyproxy/go-control-plane/blob/e42c3410afe12ff0ab77dbd5954e688a4ca59036/pkg/server/sotw/v2/server.go#L199-L205

https://github.com/envoyproxy/go-control-plane/blob/e42c3410afe12ff0ab77dbd5954e688a4ca59036/pkg/server/sotw/v2/server.go#L274

https://github.com/envoyproxy/go-control-plane/blob/e42c3410afe12ff0ab77dbd5954e688a4ca59036/pkg/server/sotw/v2/server.go#L277

https://github.com/envoyproxy/go-control-plane/blob/e42c3410afe12ff0ab77dbd5954e688a4ca59036/pkg/server/sotw/v2/server.go#L293

https://github.com/envoyproxy/go-control-plane/blob/e42c3410afe12ff0ab77dbd5954e688a4ca59036/pkg/server/sotw/v2/server.go#L301

out of them only if process finishes due to line 277 guarantees that this goroutine don't leak.

ie: if there are multiple wrong requests (with wrong type url) at the same time - it can leak, if `cache` sends wrong response - it can leak, if callbacks decide to return error - it could leak.

**Comment by fxposter** [comment]
Personally we've never seen leaks there, or at least they were not noticeable (ie: if process has 25k goroutines - if we leaked 10 during many days - that's unnoticeable in our setup).
