### ISSUE TITLE
Improper use of chan leads to panic

### ISSUE THREAD

**Issue by zuige970126** [envoyproxy/go-control-plane#789]
https://github.com/envoyproxy/go-control-plane/blob/60e8938f6a6fbed02546ee887d9923ce4ee2202e/pkg/server/sotw/v3/server.go#L154C3-L154C3
https://github.com/envoyproxy/go-control-plane/blob/60e8938f6a6fbed02546ee887d9923ce4ee2202e/pkg/server/sotw/v3/xds.go#L100

**Comment by zuige970126** [comment]
When req, err:=stream When Recv() fails to obtain (read EOF during testing), reqCh will be closed, and then reqCh<- req will be performed,

**Comment by jpeach** [comment]
@zuige970126 I see what you are saying.

 If `stream.Recv()` fails, then we return from the goroutine, closing the channel in the defer. However, in `(s *server) process()` there is second goroutine that is also writing to this same channel, which would panic. This was introduced in 717ea22d73925ee641bff3e338b200613c4ed1b7.


CC @alecholmez. Maybe we need to restructure this so that only one of `process` and `processADS` polls the channel. I't not that clear to me who is responsible for that in this code path.
