### ISSUE TITLE
 Excessive Memory Consumption in EnvoyProxy During Continuous snapshot updates for the same node

### ISSUE THREAD

**Issue by Tharsanan1** [envoyproxy/go-control-plane#882]
In my Kubernetes (k8) setup, I'm utilizing Envoy Proxy along with the Gatewayspec Httproute, and I've developed a controller for managing this Custom Resource (CR). Upon any updates to this CR, my controller generates a snapshot of the state of the world in XDS. To ensure each snapshot version is unique, I generate a random number between 0 and 100000000 during snapshot creation.

During the reconciliation process, the controller updates the snapshot with the latest state of the world using the method described in the [Go-Control-Plane Repository](https://github.com/envoyproxy/go-control-plane/blob/bac45794d399d1af65f0af7f6cd53ca4972f5a8f/pkg/cache/v3/simple.go#L78).

The issue arises when I load approximately 4000 HttpRoutes into the Kubernetes cluster, triggering around 4000 reconcile events, each of which calls the SetSnapshot method. Consequently, I observe a significant increase in router memory usage, reaching approximately ~800MB. Surprisingly, even after 10 minutes following the completion of the loading process, the memory consumption remains consistently high. However, upon restarting the router, the memory usage drops to around ~300MB.

During router restarts, only the final snapshot from the controller is retrieved. However, when the router is active, and I continuously load HttpRoutes into the cluster, the router receives the snapshot continuously with updated state of the world which is expected.

My concern is whether the EnvoyProxy implementation retains all received snapshots instead of discarding the older ones upon receiving new snapshots. The observed behavior of increasing memory usage suggests that EnvoyProxy might be storing all received snapshots, leading to excessive memory consumption.

**Comment by valerian-roche** [comment]
Hey 👋, from the description of the issue it does not seem to me that the issue is in the control-plane itself. 
It is unclear to me if the snapshot includes a single `RouteConfiguration` resource with a lot of routes or a significant number of `RouteConfiguration` updated individually. If the second case, there is a current known sub-optimal behavior as the control-plane will resend all objects on any update, even if a single has changed if you are using State-of-the-world connection from envoy. 
Overall if not using Delta XDS, I'd recommend using it to limit the amount of objects sent on changes (pending a better behavior in the control-plane for Sotw). 

For the envoy side, envoy allocator is purposefully returning memory slowly to the system, but the maximum value should remain bound. I would not expect envoy memory level to go down fast, as this would depend on the allocator behavior. You can confirm the actual memory usage through envoy heap memory endpoints.

**Comment by valerian-roche** [comment]
I would not expect envoy to store any history. The only notion of envoy caching xds resources I know of is endpoints, as the xds protocol statefulness creating some issues. 
For any question on envoy internal behavior you should open an issue on the envoy repository (https://github.com/envoyproxy/envoy/tree/main) as they would have far more context
