### ISSUE TITLE
Listener drained for every RDS update

### ISSUE THREAD

**Issue by triplewy** [envoyproxy/go-control-plane#977]
Currently have an Envoy setup where all resources (listener, clusters, routes, secrets) are generated dynamically via xDS API. I am using envoy-go-control-plane as the xDS server. 

The problem seems to be that the listener must be added to the xDS snapshot on every update to RDS because the listener references the RDS type. If it's not added, then it will fail on this snippet of code: https://github.com/envoyproxy/go-control-plane/blob/69480c45e4025c1f8a97cd8b0eafaf39b36cb2f9/pkg/cache/v3/snapshot.go#L108-L111

From my understanding of xDS protocol, if there is any update to the listener resource version, then Envoy proxy will drain the existing listener and replace it with a new one. In this case, the listener actually had no changes but its resource version must still be incremented for every RDS change, causing a listener to reload for every RDS update.

Is my understanding correct here?

**Comment by valerian-roche** [comment]
Hey, the snapshot interface does require you to provide the snapshot in every instance, but you can reset the same one. When using the state-of-the-world API, it will resend the listener if the version is changed on the snapshot for the Listener type (which it does by default). If using the delta API the control-plane will serialize and hash the listener to confirm if it has changed, and not send it if unchanged.
In either case, envoy does, on the client side, also serialize and hash the listener configuration to confirm whether it has been updated. Only if a change is detected will it update by draining connections.
From past experience, there are still two issues related to the go language, which can lead to unexpected updates:
 - use of `anypb.Any` within resources will yield a diff in the go serialized versions, due to protobuf-go randomization. This bypasses the control-plane deduplication and triggers unneeded work on the data-plane. This should not trigger listener rotation as the envoy implementation should still catch it. To avoid this you can use deterministic marshaling instead of the default `anypb.Any` constructor.
 - use of go maps in code to serialize lists yields undefined ordering that will constantly change. To avoid it you'd likely need to sort list entries. This can be observed by logging resources prior to sending them to the `go-control-plane` cache, or setting logging level in envoy to have the received resources logged.

Finally if you want to avoid it, you can set new snapshots with the same versions for listeners if you know that the version has not been changed. The API allows you to provide the different types independently. I would advise to avoid it though as if the resources actually change without the revision changing you'd end up with different clients receiving distinct configurations for the same snapshot

**Comment by triplewy** [comment]
I appreciate your response. This is exactly what I needed! I couldn't find any info if Envoy proxy checks the diff itself by hashing the xDS resources.

I had a hunch that I needed to sort the lists in some of the listener fields, particularly the TLS certificates.

Could you explain a bit more on structured marshaling? Do you have an example on how to handle the field type `*anypb.Any`, for instance HttpFilters?
